sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t plainds82/docker-react-app -f Dockerfile.dev .

script:
 - docker run -e CI=true plainds82/docker-react-app npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "ap-northeast-2"
 app: "docker-react-app"
 env: "Dockerreactapp-env"
 bucket_name: "elasticbeanstalk-ap-northeast-2-438736726455"
 bucket_path: "docker-react-app"
 on:
  branch: main

access_key_id: $AWS_ACCESS_KEY
secret_acces_key: $AWS_SECRET_ACCESS_KEY